version: '3.9'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: aiemailmarketingapp
      POSTGRES_USER: aiemailmarketingapp
      POSTGRES_PASSWORD: aiemailmarketingapp
    ports:
      - "5432:5432"

  django:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/aiemailmarketingapp
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: aiemailmarketingapp
      POSTGRES_USER: aiemailmarketingapp
      POSTGRES_PASSWORD: aiemailmarketingapp
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

