# Generated by Django 5.0.6 on 2024-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_mails', '0002_receivedemail_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='recipient_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
