# Generated by Django 5.0.6 on 2024-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_optimization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
