# Generated by Django 5.0.6 on 2024-07-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_optimization', '0003_campaign_aisentmails_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
